name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-dir: [ hello-koma, actix-gcd, wasm-calculator/calc ]
    defaults:
      run:
        working-directory: ${{ matrix.app-dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install wasm-pack
        if: matrix.app-dir == 'wasm-calculator/calc'
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: cargo build --verbose

      - name: Build wasm package
        if: matrix.app-dir == 'wasm-calculator/calc'
        run: wasm-pack build --release

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy -- -D warnings

#      - name: Check formatting　そのうち有効にする。formatくらい自動化したい。rustRoberの設定が必要
#        run: cargo fmt --check
