name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app-dir: [ hello-koma, actix-gcd ]
    defaults:
      run:
        working-directory: ${{ matrix.app-dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --verbose --workspace --timeout 120 --out Xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Check formatting
        run: cargo fmt --check
